title: Juliano Alves
subtitle: Programming Blog
description: A passioned Software Developer's Programming Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juliano-alves.com"
repository: "juliano/juliano.github.io"
twitter_username: vonjuliano
github_username:  juliano
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.20.1"

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

include:
  - _pages

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

author:
  name:          "Juliano Alves"
  avatar:        "bio-photo.png"
  bio:           "Open-source enthusiast, a firm believer that the future belongs to polyglot and functional programming"
  location:      "London, UK"
  github:        "juliano"
  linkedin:      "julianopalves"
  stackoverflow: "973740/juliano-alves"
  twitter:       "@vonjuliano"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/vonjuliano"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/juliano"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/julianopalves/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Social Sharing
twitter:
  username               : "vonjuliano"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
social:
  type                   : "Person" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/vonjuliano"
    - "https://www.linkedin.com/in/julianopalves/"
    - "https://github.com/juliano"
    - "https://speakerdeck.com/julianoalves"
    - "https://stackoverflow.com/users/973740/juliano-alves"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-151392630-1"

# SEO Related
google_site_verification : "EbmWBKPIPw7Jog9f8YX796aEjBKDtMUjyTWbQCu8B10"

comments:
  provider: "disqus"
  disqus:
    shortname: "juliano-alves"

